const malwareParts = [
      {
        id: 'ia-spearphish-attachment',
        name: 'Spearphishing Attachment',
        tactic: 'Initial Access',
        era: 'Vintage',
        stealthLevel: 'Medium',
        mitreId: 'T1566.001',
        iconEmoji: '??',
        shortDesc: 'A targeted email attachment used to deliver malware to a selected victim.',
        longDesc: 'Spearphishing attachments deliver payloads through a customized document, archive or executable. This vector has been used by Emotet and APT28 to bypass defenses by appearing legitimate.',
        howItWorks: 'An attacker sends a convincing email with a malicious attachment. When the victim opens the document, embedded macros or executables run and establish a foothold.',
        realWorldExample: 'Emotet campaigns in 2018 used invoices and shipping notices with malicious Office macros.',
        defensiveTip: 'Block suspicious attachments, enforce macro policies, inspect email content, and train users to verify unexpected documents.'
      },
      {
        id: 'ia-spearphish-link',
        name: 'Spearphishing Link',
        tactic: 'Initial Access',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1566.002',
        iconEmoji: '??',
        shortDesc: 'A malicious URL in a targeted message that leads to credential theft or exploit pages.',
        longDesc: 'Spearphishing links are tailored URLs embedded in email or chat. When the target clicks, they may reach phishing pages, exploit kits or malware downloads.',
        howItWorks: 'The attacker convinces the user to click a link and visit a site that hosts exploit code or phishing forms. That action initiates the compromise.',
        realWorldExample: 'Attackers used tailored links to breach high-profile targets in the SolarWinds campaign.',
        defensiveTip: 'Use URL scanning, phishing-resistant MFA, browser isolation, and end-user training on suspicious links.'
      },
      {
        id: 'ia-supply-chain',
        name: 'Supply Chain Compromise',
        tactic: 'Initial Access',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1195',
        iconEmoji: '??',
        shortDesc: 'Malware inserted into trusted software or updates to breach multiple customers at once.',
        longDesc: 'A supply chain compromise injects malicious code into widely distributed software. It affects many organizations because the payload is delivered through trusted channels.',
        howItWorks: 'Attackers breach a vendor or build pipeline and insert backdoors into legitimate applications or updates. Users install compromised software thinking it is safe.',
        realWorldExample: 'SolarWinds Orion 2020 used compromised update packages to deliver a remote access implant.',
        defensiveTip: 'Validate software integrity, use software bill of materials, isolate build systems, and monitor update behavior.'
      },
      {
        id: 'ia-exploit-public-facing',
        name: 'Exploit Public-Facing Application',
        tactic: 'Initial Access',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1190',
        iconEmoji: '??',
        shortDesc: 'Attacking internet-facing systems or web apps to gain a foothold.',
        longDesc: 'Public-facing applications expose services that may contain vulnerabilities. Exploiting these flaws allows remote code execution without user interaction.',
        howItWorks: 'The adversary scans for vulnerable servers and sends crafted payloads to a web app, API or database endpoint. A successful exploit gives initial access.',
        realWorldExample: 'The 2017 Equifax breach exploited a vulnerable Apache Struts application.',
        defensiveTip: 'Patch external services, use web application firewalls, and monitor logs for exploitation attempts.'
      },
      {
        id: 'ia-external-remote-services',
        name: 'External Remote Services',
        tactic: 'Initial Access',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1133',
        iconEmoji: '???',
        shortDesc: 'Abusing exposed RDP, VPN or remote access services for entry.',
        longDesc: 'Remote services are attractive targets when credentials are weak or exposed. Attackers can move from the internet into a network through these systems.',
        howItWorks: 'The attacker scans for exposed services and tries stolen or brute-forced credentials. Once authenticated, they pivot into internal hosts.',
        realWorldExample: 'Ryuk and Conti frequently used exposed RDP and VPN gateways for initial access.',
        defensiveTip: 'Limit exposure, enforce strong authentication, use conditional access, and monitor login telemetry.'
      },
      {
        id: 'ia-drive-by',
        name: 'Drive-by Compromise',
        tactic: 'Initial Access',
        era: 'Vintage',
        stealthLevel: 'High',
        mitreId: 'T1189',
        iconEmoji: '??',
        shortDesc: 'A compromised website exploits a browser or plugin when visited.',
        longDesc: 'Drive-by compromises infect victims when they visit a malicious or hacked website. The site silently runs exploit code against the browser environment.',
        howItWorks: 'The page loads exploit scripts or redirects to an exploit kit. The browser vulnerability is triggered and malware is dropped on the host.',
        realWorldExample: 'Angler and Neutrino exploit kits distributed ransomware and banking trojans in the early 2010s.',
        defensiveTip: 'Patch browsers and plugins, use content security policies, and block known malicious domains.'
      },
      {
        id: 'ia-usb-infection',
        name: 'USB / Removable Media Infection',
        tactic: 'Initial Access',
        era: 'Vintage',
        stealthLevel: 'Medium',
        mitreId: 'T1091',
        iconEmoji: '??',
        shortDesc: 'Malicious content on removable drives activates when opened.',
        longDesc: 'Infected USB drives spread malware to systems that plug them in. This method is common for air-gapped environments and insider threat scenarios.',
        howItWorks: 'A user inserts a compromised USB stick. Autorun or manually opened files execute malicious code and establish a foothold.',
        realWorldExample: 'Stuxnet in 2010 used infected USB drives to reach isolated industrial control systems in Iran.',
        defensiveTip: 'Disable autorun, scan removable media, enforce device control, and educate users about unknown drives.'
      },
      {
        id: 'ia-valid-accounts',
        name: 'Valid Accounts (Initial Access)',
        tactic: 'Initial Access',
        era: 'Vintage',
        stealthLevel: 'High',
        mitreId: 'T1078',
        iconEmoji: '??',
        shortDesc: 'Using legitimate credentials to access systems and bypass authentication defenses.',
        longDesc: 'Attackers leverage stolen or compromised accounts to enter environments without triggering many security controls.',
        howItWorks: 'Credentials are obtained through phishing, password reuse, or credential theft. The adversary logs in and proceeds with the compromise as a valid user.',
        realWorldExample: 'Ransomware groups often use stolen VPN or domain credentials for initial access.',
        defensiveTip: 'Enable MFA, rotate passwords, monitor for unusual access, and detect credential reuse.'
      },
      {
        id: 'exe-powershell',
        name: 'PowerShell',
        tactic: 'Execution',
        era: 'Current',
        stealthLevel: 'Medium',
        mitreId: 'T1059.001',
        iconEmoji: '?',
        shortDesc: 'Using PowerShell commands or scripts to execute code on Windows systems.',
        longDesc: 'PowerShell is abused by attackers for execution and post-exploitation because it can run scripts in memory and automate tasks.',
        howItWorks: 'An attacker invokes PowerShell through command line or script, then downloads payloads, injects processes, or collects data.',
        realWorldExample: 'TrickBot and Qakbot often use PowerShell for initial execution and command orchestration.',
        defensiveTip: 'Enable script block logging, restrict PowerShell usage, and monitor encoded commands and remote downloads.'
      },
      {
        id: 'exe-command-interpreter',
        name: 'Command and Scripting Interpreter (cmd)',
        tactic: 'Execution',
        era: 'Modern',
        stealthLevel: 'Low',
        mitreId: 'T1059.003',
        iconEmoji: '??',
        shortDesc: 'Using cmd.exe or shell interpreters to run commands and scripts.',
        longDesc: 'Command interpreters execute scripts and programs on demand. Attackers use them to launch payloads, modify files, and combine tools.',
        howItWorks: 'Malicious actors run commands directly or via batch files, often as part of a larger attack chain.',
        realWorldExample: 'The early WannaCry outbreak used cmd operations to execute the ransomware payload and spread laterally.',
        defensiveTip: 'Monitor command shells, restrict interpreter access, and investigate unusual batch executions.'
      },
      {
        id: 'exe-process-injection',
        name: 'Process Injection',
        tactic: 'Execution',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1055',
        iconEmoji: '??',
        shortDesc: 'Injecting code into a legitimate process to hide execution.',
        longDesc: 'Process injection conceals malicious activity inside trusted processes, making it harder for scanners to detect.',
        howItWorks: 'Malware writes shellcode into another process and then starts a thread there, running inside the host process context.',
        realWorldExample: 'FIN7 and Pawn Storm use process injection to hide command execution in browsers and system services.',
        defensiveTip: 'Detect abnormal memory writes, thread injection patterns, and suspicious parent-child process relationships.'
      },
      {
        id: 'exe-user-execution',
        name: 'User Execution',
        tactic: 'Execution',
        era: 'Vintage',
        stealthLevel: 'Low',
        mitreId: 'T1204',
        iconEmoji: '???',
        shortDesc: 'A user must open or execute malware, such as a document or installer.',
        longDesc: 'Many attacks rely on human action. If a user opens a malicious file, the payload executes and the attack proceeds.',
        howItWorks: 'The user clicks a file, runs an application, or installs software that contains malware.',
        realWorldExample: 'LockBit and Maze ransomware often rely on victim-driven execution through attachments or installers.',
        defensiveTip: 'Enforce least privilege, train users, and vet downloaded files before execution.'
      },
      {
        id: 'exe-scheduled-task',
        name: 'Scheduled Task / Job Execution',
        tactic: 'Execution',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1053',
        iconEmoji: '?',
        shortDesc: 'Creating scheduled tasks or jobs so malware runs later or repeatedly.',
        longDesc: 'Scheduled execution enables persistence and delayed action. Malicious tasks can run after reboots or at defined intervals.',
        howItWorks: 'The attacker registers a task that points to malware or a script. The OS executes it according to its trigger.',
        realWorldExample: 'Emotet creates scheduled tasks to relaunch its loader after system restarts.',
        defensiveTip: 'Monitor task creation, review task owners, and alert on unexpected scheduled jobs.'
      },
      {
        id: 'exe-wmi',
        name: 'Windows Management Instrumentation (WMI)',
        tactic: 'Execution',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1047',
        iconEmoji: '??',
        shortDesc: 'Abusing WMI to execute code remotely or schedule actions inside Windows.',
        longDesc: 'WMI provides a scriptable management interface that attackers use for remote execution and persistence.',
        howItWorks: 'A WMI script or remote command triggers code execution on a target machine without dropping new files.',
        realWorldExample: 'Advanced threats use WMI event subscriptions to run payloads from memory and avoid persistent files.',
        defensiveTip: 'Monitor WMI consumer creation, suspicious event filters, and remote WMI execution.'
      },
      {
        id: 'per-registry-run-keys',
        name: 'Registry Run Keys / Startup Folder',
        tactic: 'Persistence',
        era: 'Vintage',
        stealthLevel: 'Medium',
        mitreId: 'T1547.001',
        iconEmoji: '🔁',
        shortDesc: 'Persisting by adding entries to autorun registry keys or the startup folder.',
        longDesc: 'Autorun entries ensure malware launches after logon. This common persistence method remains effective on Windows.',
        howItWorks: 'Malware inserts a path or command into autorun keys or startup shortcuts. The OS runs the payload at user login.',
        realWorldExample: 'Zeus and many banking trojans used registry run keys to survive reboots.',
        defensiveTip: 'Audit autorun locations, alert on new or modified entries, and restrict write access.'
      },
      {
        id: 'per-scheduled-tasks',
        name: 'Scheduled Tasks',
        tactic: 'Persistence',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1053.005',
        iconEmoji: '???',
        shortDesc: 'Creating scheduled tasks to restart malware or maintain access across reboots.',
        longDesc: 'Attackers register tasks with triggers so their code executes automatically. This persistence survives reboots and logouts.',
        howItWorks: 'A Windows scheduled task is configured to launch a payload. The system executes it based on the task trigger.',
        realWorldExample: 'Ryuk and REvil used scheduled tasks to relaunch encryptors after interruptions.',
        defensiveTip: 'Detect unauthorized task creation and review scheduled jobs for suspicious commands.'
      },
      {
        id: 'per-modify-service',
        name: 'Create or Modify Windows Service',
        tactic: 'Persistence',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1543.003',
        iconEmoji: '???',
        shortDesc: 'Installing or changing services so malware starts automatically at boot.',
        longDesc: 'Windows services can run with high privileges and launch at boot. Attackers use services for stable, persistent execution.',
        howItWorks: 'Malware creates or modifies a service entry to point to its executable. The service starts automatically or on demand.',
        realWorldExample: 'LockerGoga installed services to maintain operation and complicate removal.',
        defensiveTip: 'Audit service creation and verify the paths of new service binaries.'
      },
      {
        id: 'per-wmi-subscription',
        name: 'WMI Event Subscription',
        tactic: 'Persistence',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1546.003',
        iconEmoji: '??',
        shortDesc: 'Using WMI event subscriptions to trigger code on a system event.',
        longDesc: 'WMI subscriptions attach actions to events like logon or system start, allowing malware to execute without common autorun entries.',
        howItWorks: 'Malware creates a WMI filter and consumer that responds to an event. When triggered, the subscribed action runs the payload.',
        realWorldExample: 'Advanced adversaries use WMI subscription persistence because it is harder to detect.',
        defensiveTip: 'Monitor WMI filter creation, event subscriptions, and consumer actions.'
      },
      {
        id: 'per-boot-logon',
        name: 'Boot or Logon Autostart Execution',
        tactic: 'Persistence',
        era: 'Vintage',
        stealthLevel: 'Medium',
        mitreId: 'T1547.001',
        iconEmoji: '??',
        shortDesc: 'Using boot, shell, or user logon mechanisms to restart malware.',
        longDesc: 'Modifying boot or logon autostart methods ensures malware returns after reboots and user sessions.',
        howItWorks: 'The attacker changes system startup settings or shell options so malicious code launches automatically.',
        realWorldExample: 'Worm families often modify autorun paths to keep recovering after removal efforts.',
        defensiveTip: 'Inspect boot and logon entries, and detect unusual shell changes.'
      },
      {
        id: 'per-bits-jobs',
        name: 'BITS Jobs',
        tactic: 'Persistence',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1197',
        iconEmoji: '??',
        shortDesc: 'Abusing Background Intelligent Transfer Service jobs for stealthy transfers and persistence.',
        longDesc: 'BITS moves files in the background using normal Windows APIs. Malware uses it to download payloads quietly and maintain a foothold.',
        howItWorks: 'A malicious BITS job downloads content to the host. The payload executes when the transfer completes or on demand.',
        realWorldExample: 'Post-exploitation frameworks use BITS jobs to fetch tools and avoid suspicious network activity.',
        defensiveTip: 'Monitor suspicious BITS jobs and unusual downloads from unfamiliar endpoints.'
      },
      {
        id: 'per-kernel-driver',
        name: 'Kernel Driver / Bootkit',
        tactic: 'Persistence',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1542.001',
        iconEmoji: '??',
        shortDesc: 'Installing a kernel driver or bootkit to survive reboots and hide in the OS.',
        longDesc: 'Kernel-level malware has very high privilege and can evade user-mode defenses. Bootkits infect startup to reload before the OS fully initializes.',
        howItWorks: 'The attacker installs a driver or modifies boot records so malicious code loads during system startup.',
        realWorldExample: 'Some Uroburos and advanced ransomware variants use boot kit techniques to persist through reboots.',
        defensiveTip: 'Validate driver signatures, inspect boot configuration changes, and use kernel integrity monitoring.'
      },
      {
        id: 'dev-obfuscation',
        name: 'Obfuscated Files or Information',
        tactic: 'Defense Evasion',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1027',
        iconEmoji: '??',
        shortDesc: 'Hiding code or configuration using encryption, packing, or encoding.',
        longDesc: 'Obfuscation disguises malware internals and makes static detection harder. Packed payloads are often decrypted in memory at runtime.',
        howItWorks: 'The malware is packed or encoded and then unpacked by a loader after execution.',
        realWorldExample: 'Ursnif and many RATs use packers to conceal payloads from antivirus scanners.',
        defensiveTip: 'Use dynamic analysis, memory inspection, and unpacking sandboxes to detect obfuscated behavior.'
      },
      {
        id: 'dev-process-hollowing',
        name: 'Process Hollowing',
        tactic: 'Defense Evasion',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1055.012',
        iconEmoji: '???',
        shortDesc: 'Replacing a legitimate process image with malicious code.',
        longDesc: 'Process hollowing creates a legitimate process, removes its original code, and injects a malicious payload. The process continues under a trusted name.',
        howItWorks: 'The attacker starts a benign process, unmaps its memory, writes malicious code, and resumes execution.',
        realWorldExample: 'TrickBot and banking trojans use hollowing to hide inside browsers and system services.',
        defensiveTip: 'Detect abnormal memory writes, hollowed processes, and suspicious process behavior.'
      },
      {
        id: 'dev-fileless',
        name: 'Fileless / In-Memory Execution',
        tactic: 'Defense Evasion',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1055',
        iconEmoji: '???',
        shortDesc: 'Executing malicious code directly in memory with few or no disk artifacts.',
        longDesc: 'Fileless attacks avoid disk-based detection by running entirely in memory through script hosts or code injection.',
        howItWorks: 'Malware injects shellcode into a running process or uses a scripting environment to execute code in RAM.',
        realWorldExample: 'Petya / NotPetya variants and some ransomware use in-memory execution to avoid file scanning.',
        defensiveTip: 'Monitor memory activity, script execution, and living-off-the-land binary abuse.'
      },
      {
        id: 'dev-virtualization-evasion',
        name: 'Virtualization / Sandbox Evasion',
        tactic: 'Defense Evasion',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1497',
        iconEmoji: '??',
        shortDesc: 'Detecting analysis sandboxes or VMs and altering behavior to avoid detection.',
        longDesc: 'Evasive malware checks for virtual machine artifacts, debuggers, or timing anomalies before launching its malicious payload.',
        howItWorks: 'The code probes device IDs, installed drivers, or execution timing. If it detects a lab environment, it may sleep, exit, or behave benignly.',
        realWorldExample: 'Many modern ransomware families include sandbox detection to evade automated analysis.',
        defensiveTip: 'Use diverse analysis environments and compare behavior across real and instrumented systems.'
      },
      {
        id: 'dev-masquerading',
        name: 'Masquerading',
        tactic: 'Defense Evasion',
        era: 'Vintage',
        stealthLevel: 'Medium',
        mitreId: 'T1036',
        iconEmoji: '??',
        shortDesc: 'Impersonating legitimate files, processes, or service names.',
        longDesc: 'Masquerading gives malware a trusted appearance by using familiar names or icons, reducing suspicion from users and defenders.',
        howItWorks: 'A malicious file is named like a Windows binary or placed in a trusted folder. It executes under that guise to blend in.',
        realWorldExample: 'Ransomware often masquerades as Windows updates or service executables.',
        defensiveTip: 'Validate file paths and hashes, and investigate legitimate-looking binaries launched from unusual locations.'
      },
      {
        id: 'dev-lolbins',
        name: 'Living off the Land (LOLBins)',
        tactic: 'Defense Evasion',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1218',
        iconEmoji: '??',
        shortDesc: 'Using built-in system utilities instead of custom malware binaries.',
        longDesc: 'LOLBins are legitimate tools like certutil, rundll32, and bitsadmin, abused to perform malicious actions while avoiding new files.',
        howItWorks: 'Malicious commands are written to trusted utilities, which then download, execute, or manipulate data on behalf of the attacker.',
        realWorldExample: 'APT groups often use PowerShell, certutil, and WMI to avoid dropping new malware.',
        defensiveTip: 'Monitor uncommon command lines for trusted utilities and suspicious child processes.'
      },
      {
        id: 'dev-disable-security',
        name: 'Disable or Modify Security Tools',
        tactic: 'Defense Evasion',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1562.001',
        iconEmoji: '???',
        shortDesc: 'Turning off or altering antivirus, EDR, or logging tools.',
        longDesc: 'Attackers disable security products to reduce detection while malware operates. This can include stopping services or deleting logs.',
        howItWorks: 'Malware stops protective agents, modifies drivers, or clears event history to weaken the defender�s visibility.',
        realWorldExample: 'Ransomware often disables Windows Defender and security services before encryption.',
        defensiveTip: 'Monitor service stoppages, agent modifications, and log deletion activity.'
      },
      {
        id: 'dev-clear-history',
        name: 'Clear Command History',
        tactic: 'Defense Evasion',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1070.004',
        iconEmoji: '??',
        shortDesc: 'Removing shell and command history to hinder investigation.',
        longDesc: 'Attackers delete command histories and logs to reduce forensic evidence and make detection harder.',
        howItWorks: 'The adversary overwrites or deletes history files, PowerShell logs, or event records after running commands.',
        realWorldExample: 'Advanced actors clear bash history and Windows event logs during lateral movement.',
        defensiveTip: 'Detect history clearing commands and preserve forensic copies before logs are modified.'
      },
      {
        id: 'pri-exploit-escalation',
        name: 'Exploitation for Privilege Escalation',
        tactic: 'Privilege Escalation',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1068',
        iconEmoji: '??',
        shortDesc: 'Using a vulnerability to raise privileges on a compromised host.',
        longDesc: 'Privilege escalation exploits flaws in the OS or applications to move from a limited user to admin or system access.',
        howItWorks: 'The attacker triggers a software vulnerability and executes code with higher privileges.',
        realWorldExample: 'Many ransomware campaigns use kernel exploits or service vulnerabilities to gain system control.',
        defensiveTip: 'Patch escalation vulnerabilities, enforce exploit mitigations, and monitor privilege changes.'
      },
      {
        id: 'pri-uac-bypass',
        name: 'Bypass User Account Control (UAC)',
        tactic: 'Privilege Escalation',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1548.002',
        iconEmoji: '??',
        shortDesc: 'Abusing UAC weaknesses to execute code with higher privileges without prompts.',
        longDesc: 'UAC bypass tricks Windows into elevating a process without user consent, letting attackers avoid the prompt flow.',
        howItWorks: 'Malware abuses auto-elevated processes or bypass mechanisms to launch code as administrator.',
        realWorldExample: 'Threat actors use UAC bypass chains after initial compromise to gain higher rights.',
        defensiveTip: 'Harden UAC settings, block known bypass binaries, and watch for suspicious elevation behavior.'
      },
      {
        id: 'pri-access-token',
        name: 'Access Token Manipulation',
        tactic: 'Privilege Escalation',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1134',
        iconEmoji: '??',
        shortDesc: 'Reusing or forging access tokens to impersonate higher-privileged accounts.',
        longDesc: 'Token manipulation lets attackers operate as another user or service without needing the actual credentials.',
        howItWorks: 'The malware steals a token from a privileged process or forges one using available credentials, then uses it to authenticate.',
        realWorldExample: 'Credential theft tools manipulate tokens to move laterally as SYSTEM or Domain Admin.',
        defensiveTip: 'Monitor token impersonation and suspicious process token usage.'
      },
      {
        id: 'pri-setuid',
        name: 'Setuid / Setgid Abuse',
        tactic: 'Privilege Escalation',
        era: 'Current',
        stealthLevel: 'Medium',
        mitreId: 'T1166',
        iconEmoji: '??',
        shortDesc: 'Abusing setuid or setgid binaries on Unix-like systems for elevated access.',
        longDesc: 'Setuid/setgid allows binaries to run with owner privileges. Attackers can exploit misconfigured executables to escalate privileges.',
        howItWorks: 'A malicious or hijacked setuid binary runs with root or another privileged account.',
        realWorldExample: 'Linux intrusions often use setuid binaries to pivot from normal users to root.',
        defensiveTip: 'Audit setuid/setgid files, restrict their use, and detect unusual privilege escalations.'
      },
      {
        id: 'pri-sudo-caching',
        name: 'sudo / sudo caching abuse',
        tactic: 'Privilege Escalation',
        era: 'Current',
        stealthLevel: 'Low',
        mitreId: 'T1548.003',
        iconEmoji: '??',
        shortDesc: 'Abusing cached sudo credentials or weak sudo policies.',
        longDesc: 'On Linux, sudo may remember authentication for a time. Attackers can abuse that cached privilege to run commands as root.',
        howItWorks: 'The adversary leverages an existing sudo session or permissive sudo configuration to execute privileged actions.',
        realWorldExample: 'Ransomware on Linux servers has exploited stale sudo caches for escalation.',
        defensiveTip: 'Require reauthentication and audit sudo usage.'
      },
      {
        id: 'cred-lsass',
        name: 'OS Credential Dumping (LSASS)',
        tactic: 'Credential Access',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1003.001',
        iconEmoji: '??',
        shortDesc: 'Extracting credentials from the Windows LSASS process.',
        longDesc: 'LSASS stores credentials and tickets for logged-on users. Malware dumps its memory to harvest hashes, tickets, and plaintext passwords.',
        howItWorks: 'The attacker reads LSASS memory or uses tools like Mimikatz to extract credential material.',
        realWorldExample: 'Mimikatz-style credential dumping is a common step in advanced intrusions.',
        defensiveTip: 'Protect LSASS memory, enable Credential Guard, and monitor suspicious process access to LSASS.'
      },
      {
        id: 'cred-browser-passwords',
        name: 'Credentials from Web Browsers / Password Stores',
        tactic: 'Credential Access',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1505.003',
        iconEmoji: '??',
        shortDesc: 'Stealing saved browser passwords, cookies, and tokens.',
        longDesc: 'Browsers store sensitive credentials for convenience. Malware can scrape that data and reuse it for further access.',
        howItWorks: 'The attacker reads protected browser storage and decrypts credentials, cookies, or other authentication secrets.',
        realWorldExample: 'Infostealers often harvest saved credentials from Chrome, Firefox, and Edge.',
        defensiveTip: 'Protect browser stores, use MFA, and monitor for suspicious credential access.'
      },
      {
        id: 'cred-keylogger',
        name: 'Input Capture (Keylogger)',
        tactic: 'Credential Access',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1056.001',
        iconEmoji: '??',
        shortDesc: 'Recording keystrokes to capture passwords and sensitive input.',
        longDesc: 'Keyloggers monitor keyboard activity and send captured data to attackers. They can be installed as drivers, hooks, or malicious apps.',
        howItWorks: 'Malware hooks input events or reads raw keyboard buffers and stores keystrokes for later exfiltration.',
        realWorldExample: 'Financial malware often includes keylogger modules to steal credentials in real time.',
        defensiveTip: 'Detect hook injection and keyboard monitoring processes, and limit privileged key logging access.'
      },
      {
        id: 'cred-kerberos-theft',
        name: 'Kerberos Ticket Theft / Golden Ticket',
        tactic: 'Credential Access',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1558.001',
        iconEmoji: '??',
        shortDesc: 'Stealing or forging Kerberos tickets for lateral access.',
        longDesc: 'Kerberos ticket abuse lets attackers impersonate users and access services without passwords.',
        howItWorks: 'The adversary extracts TGTs from memory or forges Golden Tickets with domain keys to access resources.',
        realWorldExample: 'NotPetya and advanced threats use ticket theft to move laterally in Windows domains.',
        defensiveTip: 'Protect domain controllers, monitor Kerberos activity, and rotate krbtgt keys.'
      },
      {
        id: 'lat-remote-services',
        name: 'Remote Services (PsExec/WMI/RDP)',
        tactic: 'Lateral Movement',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1021',
        iconEmoji: '??',
        shortDesc: 'Using remote management tools to move laterally across hosts.',
        longDesc: 'Attackers use tools like PsExec, WMI, and RDP to execute commands on other systems within the network.',
        howItWorks: 'A compromised host authenticates to another system and runs malware or administrative tasks remotely.',
        realWorldExample: 'Ransomware groups often use PsExec to deploy encryptors across multiple machines.',
        defensiveTip: 'Limit remote admin tools, control lateral credentials, and monitor remote execution patterns.'
      },
      {
        id: 'lat-pass-hash',
        name: 'Pass the Hash / Pass the Ticket',
        tactic: 'Lateral Movement',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1550.002',
        iconEmoji: '??',
        shortDesc: 'Reusing stolen authentication tokens instead of cracking passwords.',
        longDesc: 'Pass-the-hash and pass-the-ticket let attackers authenticate to other systems using stolen credentials or tickets.',
        howItWorks: 'Stolen hashes or tickets are replayed against target systems, granting access without plaintext passwords.',
        realWorldExample: 'WannaCry and other outbreaks relied on credential replay during propagation.',
        defensiveTip: 'Segment networks, enforce strong authentication, and detect credential reuse.'
      },
      {
        id: 'lat-tool-transfer',
        name: 'Lateral Tool Transfer',
        tactic: 'Lateral Movement',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1570',
        iconEmoji: '??',
        shortDesc: 'Moving tools or malware to another host to continue the attack.',
        longDesc: 'Lateral tool transfer copies utilities or payloads to remote systems for further actions.',
        howItWorks: 'The adversary transfers a binary or script to a remote host and executes it there.',
        realWorldExample: 'Espionage campaigns move credential harvesters to multiple hosts to expand access.',
        defensiveTip: 'Detect unexpected file transfers and remote execution requests between hosts.'
      },
      {
        id: 'lat-rdp',
        name: 'Remote Desktop Protocol',
        tactic: 'Lateral Movement',
        era: 'Modern',
        stealthLevel: 'High',
        mitreId: 'T1021.001',
        iconEmoji: '???',
        shortDesc: 'Using RDP sessions to control remote systems interactively.',
        longDesc: 'RDP provides a full desktop session on another machine. Attackers use stolen credentials to operate as if local.',
        howItWorks: 'The adversary logs into a remote host via RDP and performs actions manually or with scripts.',
        realWorldExample: 'RDP is popular with ransomware actors for exploration and deployment in victim networks.',
        defensiveTip: 'Restrict RDP exposure, use jump hosts, and monitor remote desktop connections.'
      },
      {
        id: 'c2-application-layer',
        name: 'Application Layer Protocol (Web/HTTPS)',
        tactic: 'Command and Control',
        era: 'Current',
        stealthLevel: 'Medium',
        mitreId: 'T1071.001',
        iconEmoji: '??',
        shortDesc: 'Hiding C2 traffic inside web or HTTPS communications.',
        longDesc: 'C2 over web protocols blends malicious communication with allowed traffic, making it harder to spot.',
        howItWorks: 'Malware sends encrypted commands over HTTP/HTTPS to a control server, often mimicking normal browsing traffic.',
        realWorldExample: 'Many RATs use HTTPS-based C2 to evade network filtering.',
        defensiveTip: 'Inspect outbound web traffic and use SSL inspection where possible.'
      },
      {
        id: 'c2-dns-tunneling',
        name: 'DNS Tunneling',
        tactic: 'Command and Control',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1071.004',
        iconEmoji: '??',
        shortDesc: 'Using DNS queries and responses as a covert communication channel.',
        longDesc: 'DNS is often allowed through firewalls, so attackers tunnel commands and data through DNS requests.',
        howItWorks: 'Malware encodes data into DNS queries and sends them to attacker-controlled servers, receiving commands back in responses.',
        realWorldExample: 'Advanced persistent threats have used DNS tunneling to maintain covert contact in restricted environments.',
        defensiveTip: 'Monitor DNS query patterns and unusual domain names.'
      },
      {
        id: 'c2-remote-access-software',
        name: 'Remote Access Software (RATs)',
        tactic: 'Command and Control',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1219',
        iconEmoji: '???',
        shortDesc: 'Using RATs to control systems and gather information remotely.',
        longDesc: 'RATs provide persistent remote control capabilities that attackers use for reconnaissance and data theft.',
        howItWorks: 'A RAT installs on the target and connects back to a command server for instructions.',
        realWorldExample: 'Agent Tesla and Gh0st RAT are common remote access tools in crimeware and espionage.',
        defensiveTip: 'Block known RAT servers and inspect unusual remote access activity.'
      },
      {
        id: 'c2-web-service',
        name: 'Web Service C2 (Dropbox/GitHub/Telegram)',
        tactic: 'Command and Control',
        era: 'Current',
        stealthLevel: 'Medium',
        mitreId: 'T1102',
        iconEmoji: '??',
        shortDesc: 'Using popular cloud or messaging services as C2 infrastructure.',
        longDesc: 'Attackers hide C2 traffic in services like GitHub, Dropbox or Telegram that are normally allowed.',
        howItWorks: 'Malware polls a public service for encoded commands or uploads data to a shared repository.',
        realWorldExample: 'Some malware families use GitHub Gists and Telegram bots for command channels.',
        defensiveTip: 'Monitor service account access and restrict unapproved cloud service communication.'
      },
      {
        id: 'c2-proxy-domain-fronting',
        name: 'Multi-hop Proxy / Domain Fronting',
        tactic: 'Command and Control',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1090.003',
        iconEmoji: '??',
        shortDesc: 'Hiding C2 traffic behind trusted domains or proxy chains.',
        longDesc: 'Domain fronting makes malicious traffic appear to go to a legitimate site while it reaches an attacker-controlled endpoint.',
        howItWorks: 'Malware sends requests through a proxy chain or uses a different front-end host header to conceal the destination.',
        realWorldExample: 'Some state-sponsored actors used domain fronting to evade detection and censorship.',
        defensiveTip: 'Inspect TLS/SNI mismatches and block untrusted tunneling services.'
      },
      {
        id: 'col-local-system',
        name: 'Data from Local System',
        tactic: 'Collection',
        era: 'Vintage',
        stealthLevel: 'Low',
        mitreId: 'T1005',
        iconEmoji: '??',
        shortDesc: 'Gathering files, credentials, and artifacts from a compromised host.',
        longDesc: 'Local collection retrieves sensitive information from the machine itself for later exfiltration or analysis.',
        howItWorks: 'Malware searches for documents, databases, and system files, then stages them for transfer.',
        realWorldExample: 'Infostealers harvest local data before exfiltration in many campaigns.',
        defensiveTip: 'Monitor unusual file access and protect sensitive directories.'
      },
      {
        id: 'exp-ransomware',
        name: 'Data Encrypted for Impact (Ransomware)',
        tactic: 'Impact',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1486',
        iconEmoji: '??',
        shortDesc: 'Encrypting files or systems to disrupt operations and demand payment.',
        longDesc: 'Ransomware locks data and often includes extortion tactics, making recovery dependent on backups or decryption.',
        howItWorks: 'The malware encrypts critical files and displays a ransom demand while preventing normal access.',
        realWorldExample: 'WannaCry 2017 and LockBit 2021 caused major outages with file encryption.',
        defensiveTip: 'Maintain offline backups, isolate infected hosts, and detect mass encryption activity.'
      },
      {
        id: 'imp-recovery-inhibit',
        name: 'Inhibit System Recovery',
        tactic: 'Impact',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1490',
        iconEmoji: '???',
        shortDesc: 'Disabling recovery services and backups to make remediation harder.',
        longDesc: 'Inhibiting recovery removes options for restoring systems after an attack by deleting backups or disable recovery mechanisms.',
        howItWorks: 'Malware deletes shadow copies, disables backup services, or corrupts restore points.',
        realWorldExample: 'Ryuk and other ransomware variants delete Volume Shadow Copies before encryption.',
        defensiveTip: 'Protect backup systems, segment recovery infrastructure, and monitor recovery artifacts.'
      },
      {
        id: 'imp-destruction',
        name: 'Data Destruction / Wiper',
        tactic: 'Impact',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1485',
        iconEmoji: '??',
        shortDesc: 'Overwriting or wiping data to permanently destroy it.',
        longDesc: 'Wiper malware destroys files and disks instead of stealing them, causing long-term damage.',
        howItWorks: 'The malware overwrites files or corrupts boot sectors, making recovery difficult without backups.',
        realWorldExample: 'Shamoon and NotPetya wiped systems in destructive campaigns.',
        defensiveTip: 'Protect backups, isolate compromised systems, and detect mass deletion behavior.'
      },
      {
        id: 'exp-resource-hijack',
        name: 'Resource Hijacking (Cryptomining)',
        tactic: 'Impact',
        era: 'Current',
        stealthLevel: 'Low',
        mitreId: 'T1496',
        iconEmoji: '??',
        shortDesc: 'Using compromised hosts to mine cryptocurrency or consume compute resources.',
        longDesc: 'Cryptomining malware runs in the background, degrading system performance while generating profit for attackers.',
        howItWorks: 'The malware installs a miner and connects to a pool to leverage the host�s CPU or GPU.',
        realWorldExample: 'Cryptomining campaigns target.Cloud servers and endpoints with weak controls.',
        defensiveTip: 'Monitor unexpected CPU/GPU usage and unauthorized network connections to mining pools.'
      },
      {
        id: 'exp-c2-exfil',
        name: 'Exfiltration Over C2 Channel',
        tactic: 'Exfiltration',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1041',
        iconEmoji: '??',
        shortDesc: 'Sending stolen data through the same covert C2 channel.',
        longDesc: 'Exfiltration over C2 avoids separate data transfer mechanisms and blends stolen data into existing command traffic.',
        howItWorks: 'Data is encoded into the malicious C2 protocol and transmitted to the attacker-controlled server.',
        realWorldExample: 'Espionage groups use C2 channels to quietly steal sensitive documents.',
        defensiveTip: 'Inspect C2 traffic for unusual payloads and upload behavior.'
      },
      {
        id: 'exp-compress-before-exfil',
        name: 'Data Compressed before Exfil',
        tactic: 'Exfiltration',
        era: 'Modern',
        stealthLevel: 'Medium',
        mitreId: 'T1560.001',
        iconEmoji: '??',
        shortDesc: 'Compressing data before sending it to reduce transfer volume.',
        longDesc: 'Compressing exfiltrated data makes transfers smaller and less conspicuous, especially when combined with encryption.',
        howItWorks: 'Malware archives target files before transmitting them to minimize size and evade detection.',
        realWorldExample: 'Data theft operations compress large file sets before exfiltration.',
        defensiveTip: 'Monitor archive creation and large transfer events from sensitive locations.'
      },
      {
        id: 'exp-account-removal',
        name: 'Account Access Removal',
        tactic: 'Impact',
        era: 'Current',
        stealthLevel: 'High',
        mitreId: 'T1531',
        iconEmoji: '??',
        shortDesc: 'Deleting or disabling accounts to lock out defenders and maintain control.',
        longDesc: 'Removing accounts hinders incident response and helps attackers persist by eliminating access for legitimate users.',
        howItWorks: 'The attacker disables or deletes users, changes passwords, or removes recovery options.',
        realWorldExample: 'Ransomware campaigns sometimes lock IT teams out by modifying accounts.',
        defensiveTip: 'Detect unexpected account changes and privileged modification activity.'
      }
    ]
console.log(malwareParts.length)